Aligned tool naming from EventStoreDB Cloud Console to Event Store Cloud Console
EventStore/esc pull request #60
Opened 2021-03-12 10:35 UTC by oskardudycz

2021-03-12 10:42 UTC, DanielWarrenES requested changes
"Even Store" in line 1 should be "Event Store"

2021-03-12 10:43 UTC, DanielWarrenES requested changes

2021-03-12 10:43 UTC, DanielWarrenES commented on README.md
> +# Even Store Cloud CLI
Should be "Event Store"

2021-03-12 10:52 UTC, oskardudycz commented on README.md
> +# Even Store Cloud CLI
Fixed 👍

2021-03-12 11:05 UTC, DanielWarrenES approved these changes

2021-03-15 08:18 UTC, ylorph approved these changes

2021-03-15 08:18 UTC, alexeyzimarev approved these changes

2021-03-15 08:19 UTC, merged